sudo: required
services:
  - docker

before_install:
  - docker build -t brlewis23/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brlewis23/multi-docker-test npm test

after_success:
  - docker build -t brlewis23/multi-docker-client ./client
  - docker build -t brlewis23/multi-docker-nginx ./nginx
  - docker build -t brlewis23/multi-docker-server ./server
  - docker build -t brlewis23/multi-docker-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Now we need to push these images to docker hub
  - docker push brlewis23/multi-docker-client
  - docker push brlewis23/multi-docker-nginx
  - docker push brlewis23/multi-docker-server
  - docker push brlewis23/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-794740421100
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY